name: IAC PROVISION

on:
  # push:
  #   branches: [main]
  pull_request: 
    branches: [main, develop]
    paths-ignore: # just update docs -> skip
      - '**.md'
      - '**.txt'
      - 'docs/**'
      - '.github/workflows/**'
    types: [opened, synchronize]
  workflow_dispatch: 

# Permission for GITHUB_TOKEN (Security Best Practice)  
permissions: 
  contents: read

env:
  TEST_ENV_VAR: 123456
  API_KEY: ${{secrets.API_KEY}}
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
  DOCKERHUB_REPO_NAME: dop2025.shopsquare.frontend

jobs: 
  provision_infra:
    runs-on: self-hosted
    steps:
      - name: Update OS
        run: |
          sudo apt-get update
          sudo apt-get install -y libatomic1
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.3"
        
      - name: Terraform Check 
        run: |
          terraform --version
          terraform validate

  # code_quality_check:
  #   runs-on: self-hosted
  #   strategy:
  #     fail-fast: false # if a job failed, another jobs still run and return a result.
  #   steps:
  #     - name: Update OS
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y libatomic1

  #     - name: Checkout Repo
  #       uses: actions/checkout@v6
  #       # with:
  #       #   fetch-depth: 0 #! get all git history (neccessary for some analysis tools)

  #     - name: Install Runtime
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: latest
  #         cache: 'npm'

  #     - name: Run Fail Test
  #       run: npm run fail

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Check Code Format/Convention
  #       run: npm run lint

  #     - name: Run Test
  #       run: npm run test

      # - name: Check Docker Environment 
      #   run: |
      #     docker --version
      #     docker compose version

      # - name: Install Docker
      #   uses: docker/setup-docker-action@v4
      
      # - name: Test Docker 
      #   run: echo "$(docker --version) || $(docker compose version)"
      
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ env.DOCKERHUB_USERNAME }}
      #     password: ${{ env.DOCKERHUB_PASSWORD }}

      # - name: Build and Push 
      #   uses: docker/build-push-action@v6
      #   with: 
      #     context:
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{env.DOCKERHUB_USERNAME}}/${{env.DOCKERHUB_REPO_NAME}}
