name: IAC Manually Trigger Provision

on:
  workflow_dispatch:

permissions: 
  id-token: write
  contents: read
  pull-requests: write

env: 
  TF_VERSION: latest
  AWS_REGION: ap-northeast-2
  AWS_IAM_ID: ${{secrets.AWS_IAM_ID}}

jobs:
  manually-trigger-provision:
    name: Manually Trigger Provision
    runs-on: dop10_self_hosted_runner_01
    steps:
      - name: Update OS
        run: |
          sudo apt-get update
          sudo apt-get install -y libatomic1 unzip
          
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_IAM_ID}}:role/GithubActionsDeployRole
          aws-region: ${{env.AWS_REGION}}
      
      - name: AWS connect check
        run: aws s3 ls # aws sts get-caller-identity

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v3
      #   with:
      #     terraform_version: ${{env.TF_VERSION}}
      
      # - name: Terraform Init
      #   run: terraform init -backend-config="bucket=my-state-bucket"
      
      # - name: Terraform Format 
      #   run: |
      #     terraform fmt -check 
      #     terraform validate
      