name: MANUAL TRIGGER

on: 
  workflow_dispatch: 
    inputs:
      name: 
        description: "Who to greet?"
        required: true
        default: "World"

jobs:
  welcome_manual_trigger_success:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Trigger Successful
        run: echo "Manual Trigger Successfully!"
      - name: Say Hello
        run: echo "Hello ${{github.event.inputs.name}}"
