name: PULL REQUEST OPENED

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main, develop]
    paths-ignore: # just update docs -> skip
      - ‘**.md’
      - 'docs/**'
      - '.github/workflows/**'
    types: [opened, synchronize]
  workflow_dispatch: 

# Permission for GITHUB_TOKEN (Security Best Practice)  
permissions: 
  contents: read

env:
  TEST_ENV_VAR: 123456
  API_KEY: ${{secrets.API_KEY}}

jobs: 
  welcome_pull_request_opened_success:
    runs-on: ubuntu-latest
    steps: 
      - name: Pull Request Opened Successfully!
        run: echo "Pull Request Opened Successfully!"
      - name: Get environment data
        run: echo "TEST_ENV_VAR ~ $TEST_ENV_VAR || API_KEY ~ $API_KEY" # output: `TEST_ENV_VAR ~ 123456 || API_KEY ~ ***`
  
  code_quality_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        # with:
        #   fetch-depth: 0 #! get all git history (neccessary for some analysis tools)

      - name: Install Runtime
        uses: actions/setup-node@v6
        with:
          node-version: latest
          # cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Check Code Format/Convention
        run: npm run lint

      - name: Run Test
        run: npm run test
      
      - name: Check Supported Git Variables
        run: printenv
      
