name: PULL REQUEST CLOSED

on:
  pull_request: 
    branches: [main]
    types: [closed]

jobs: 
  welcome_pull_request_closed_success:
    runs-on: ubuntu-latest
    steps: 
      - name: Pull Request Closed/Merged Successfully!
        run: echo "Pull Request Closed/Merged Successfully! =))"
