name: PULL REQUEST OPENED

on:
  pull_request: 
    branches: [main, develop]
    types: [opened, synchronize]

jobs: 
  welcome_pull_request_opened_success:
    runs-on: ubuntu-latest
    steps: 
      - name: Pull Request Opened Successfully!
        run: echo "Pull Request Opened Successfully!"
